import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Script from "next/script";
import dynamic from "next/dynamic";
const PuterAuthGate = dynamic(() => import("@/components/PuterAuthGate"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mock Interview App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <PuterAuthGate />
          {children}
          
          {/* Google AdSense */}
          <Script
            async
            src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8880385119289443"
            crossOrigin="anonymous"
            strategy="afterInteractive"
          />
          
          {/* Google Analytics */}
          <Script
            strategy="afterInteractive"
            src="https://www.googletagmanager.com/gtag/js?id=G-EX6CJQSZY4"
          />
          <Script id="google-analytics" strategy="afterInteractive">
            {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-EX6CJQSZY4');
            `}
          </Script>
        </body>
      </html>
    </ClerkProvider>
  );
}
